trigger: url_builder_II
title: Url builder II
description: Use this tool to build stardardized Urls
surfaces:
- issue
steps:
- type: form
  style: embedded
  body:
  - type: dropdown
    attributes:
      label: utm_medium
      description: Select campaign medium
      options:
      - label: paid_social
        value: utm_medium=paid_social
      - label: org_social
        value: utm_medium=org_social
      - label: email
        value: utm_medium=email
      - label: ppc
        value: utm_medium=ppc
      - label: inmail
        value: utm_medium=inmail
      - label: video
        value: utm_medium=video
      - label: product
        value: utm_medium=product
      - label: referral
        value: utm_medium=referral
  - type: dropdown
    attributes:
     label: utm_source
     description: Select campaign source
     options:
      - label: announcement
        value: utm_source=announcement
      - label: facebook
        value: utm_source=facebook
      - label: github
        value: utm_source=github
      - label: google
        value: utm_source=google
      - label: instagram
        value: utm_source=instagram
      - label: linkedin
        value: utm_source=linkedin
      - label: msft
        value: utm_source=msft
      - label: newsletter
        value: utm_source=newsletter
      - label: outreach
        value: utm_source=outreach
      - label: pinterest
        value: utm_source=pinterest
      - label: twitter
        value: utm_source=twitter
      - label: youtube
        value: utm_source=youtube
      - label: G2
        value: utm_source=G2
      - label: Capterra
        value: utm_source=Capterra
  - type: input
    attributes:
      label: utm_campaign
      description: Please add the campaign name only. `utm_campaign=` will be populated automatically. 
      placeholder: 2022Q2-wbr-APAC-JP-DevSecOps2
  - type: input
    attributes:
      label: scid
      description: Please populate the SFDC campaign id for your campaign in this field. 
      placeholder: 7013o000002CbkLAAS
  - type: input
    attributes:
      label: root_url
      description: Add the root url without the `?`. We will add that part automatically for you.
      placeholder: https://resources.github.com/
- type: fill
  template: "Your url is: {{ data.root_url }}?&{{ data.utm_medium }}&{{ data.utm_source }}&utm_campaign={{ data.utm_campaign }}&scid={{ data.scid }}"
